name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: 🚀 Features
    label: feature

  - title: 🐛 Bug Fixes
    labels: fix

  - title: 🧰 Maintenance
    label: chore

change-template: "- $TITLE (#$NUMBER) @CONTRIBUTORS"
template: |
  ## Changes

  $CHANGES
